// This file is auto-generated by scripts/generate-gallery-manifest.mjs
// Do not edit this file directly.

export interface GalleryImage {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const galleryImages: GalleryImage[] = [
  {
    src: "/gallery/Copy of DSC06664.jpg",
    width: 4357,
    height: 6536,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AKGfhtfJuf796wDBvLIjKQaaoIMAvL26AAkAtLCnAMTCwLq2tMnFwMC8FkNIV8KdAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC06694.jpg",
    width: 4625,
    height: 6938,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AGBbS21hXNjU0QCMlH7//fjt5doAzsu71ci6jn1uABwjEH9yZxEAALo0E8hONEv7AAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC06710 (1).jpg",
    width: 4482,
    height: 6723,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AKCaklZJP7ayrwDy7ef18e7X0MYA//z39O3lcWJTAIeAeWdeVxIEAO5FFlntnlwMAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC06719.jpg",
    width: 4562,
    height: 6843,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMUlEQVR4nGNo6m15+vHLl///GTwc1TOi3GqKMxnmddbd3LXYRoufoTI9PDXUhZeFAQCanBD2huWVcQAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/Copy of DSC06732.JPEG",
    width: 4575,
    height: 6862,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMUlEQVR4nGNIKwp68OTRl9//GXSUGWQYGNjEGBjO7dxQGethyMrAsHPlnJbMYBkGBgBHfA4rLdaPRwAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/Copy of DSC06813.jpg",
    width: 7008,
    height: 4672,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMklEQVR4nAEnANj/APH///r28cjAtqikoAC5u77p4NqvpZtpZl8AKiEWfW1jbmljAAIA/7MU17jPNDQAAAAASUVORK5CYII=",
  },
  {
    src: "/gallery/Copy of DSC06848.jpg",
    width: 4486,
    height: 6729,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/APX19/v7/P7//wDGxseqqKf4/v8AfnNpXEk6vbeyAGY5JBkAABwSAi6FFXztfXtOAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07000.jpg",
    width: 4672,
    height: 7008,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AAANAB0jAGxzUgAiKwBpW0dHQCQAztej+Onk+PLtAP/8/+3n4fLv6wLRE+Eq+hMzAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07050.JPEG",
    width: 4615,
    height: 6922,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGNgUBQIzYlmkOFisPCz/vn/jYqtCgOrDOOMvmZFa3UGbgUR30hfBkEGAMQMCS9/4hpsAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07054.jpg",
    width: 4447,
    height: 6671,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMUlEQVR4nGNoXtz55P9zCTtVBkkd/qDcQB0HVYa9O5ft2LeCV4yBISY76uiRXQz8DAA9dQ66gcXIBAAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/Copy of DSC07138.jpg",
    width: 4234,
    height: 6351,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/ACM9Jk1nSQglDQDU783s99qrx6YA4/bV2tC9lqODADhJM3JpVwIWAG2QEfJM1BNXAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07144.JPEG",
    width: 4642,
    height: 6963,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AA8uHT5iSQAQAADI6M/i89rH5tAA0u7U//nnxNzFACg8LH14cAAOAHDuEtrQmLb9AAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07291.JPEG",
    width: 4575,
    height: 6862,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AIGhjTM7HAAIAACTqpq+tK0kJQ8A+/360sW9jX92AN/SzcC2rXhtZU/0E0MH9hheAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07408.JPEG",
    width: 6752,
    height: 4501,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMklEQVR4nAEnANj/AEdTKxgBAFRLOMvFrgC5vZx6b2C7r6O+wKoA/vn2qZ+U4d/VrKyjS7EU3bB/+r0AAAAASUVORK5CYII=",
  },
  {
    src: "/gallery/Copy of DSC07487.jpg",
    width: 14016,
    height: 9344,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGPQ1hbqnxQvL8ZQW5XKkJsV8v/Po+XTm8oqExiMtdXnT5k4saOMgY0BABbXDm8seBhLAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07512.jpg",
    width: 4645,
    height: 6967,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/AE5aPxojCCoaAAAcBgBnYVP/+NkAYVVF3NHKrKCSAHNyadjVzZycmvoZEGiUawVYAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07519.jpg",
    width: 4651,
    height: 6977,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/ACkxGoKJcg4KAABeUDr//PG5qZQAKSMTvbOlmZGDAG5rX83KvrOvpyqIEYtQieRZAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07548.jpg",
    width: 6898,
    height: 4599,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGNQVGZtakybPb9e31CEITvB7P/3O//enEoO0mLgYmIozHK+d3ZuRVEkACcFD/tUP6D0AAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07580.jpg",
    width: 7008,
    height: 4672,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGN4+vLetz8vZ82tYOZiYMjKcQkJ0qovjjc3E2GY0lc3s7t6Tn9terw/AG8HEPzg9vBoAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07603.jpg",
    width: 7008,
    height: 4672,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGP49+/f69ev582bx8zMzJCZmSkhIdHf3x8cHMzQ1dXV2tpaVlaWlpYGAH4dEYmgoEeVAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07607.jpg",
    width: 6721,
    height: 4481,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGNYvLjn/4/Pj+5efvjoOoMYB4M8D4OGDIOpNguDHC9DVpxXS2WqpaYYAGOyDfE4EZO2AAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07624.jpg",
    width: 6667,
    height: 4445,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGMI9VGoz/Kc1hiXEKvOIMvCoKfMYGHA62ooxDCnu+j5tcP/fz25fWYbAN9rDw9k+SlLAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07643.jpg",
    width: 4573,
    height: 6860,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMUlEQVR4nGMwkGaQZ2BQFWdgyAwyn1YZW5ntw7CgM+//t+ebFrYzdES4ru0pP7tqCgDkxg9iEuD+WwAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/Copy of DSC07653.jpg",
    width: 4513,
    height: 6769,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAM0lEQVR4nAEoANf/ABcCAD4pD1o/IQBZLgCcf0zQyIwA17aRqpdtaW09AP/77/jr3cK7rwQlEhDAJaPjAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07683.jpg",
    width: 6628,
    height: 4419,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGOY0plfmOw9pSW3LNuHQUOaQYqZwVCLX5qBgWF+d973pyf+f7tz6eAqAPw3D42Xc1QGAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/Copy of DSC07737-Enhanced-NR.JPEG",
    width: 4553,
    height: 6829,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMUlEQVR4nGOw1BBXlpMUYGZgmDOp3F2XL9lNiWHf1imrp1cr8jMwXDt74N/f39WNbQDT9Q6nsRBcwgAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/Copy of DSC07769.jpg",
    width: 4565,
    height: 6848,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMUlEQVR4nGMIdZBWZGBQYWBgmNwcmuQkHmPKxDCtLXDvkjpDGQaG49tm///5YufmZQDI7A5SVMYbXwAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/Copy of DSC07989.jpg",
    width: 6721,
    height: 4481,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAACTpAAAk6QFQJOf4AAAAMElEQVR4nGOQNWFgEGDYtWVjQ08Dg4YzQ06abXlafHqGFcOWTRP+//588cjuLB8bAPyzD/Fl2ERUAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_Full Res-17.jpg",
    width: 5472,
    height: 3648,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAMklEQVR4nAEnANj/AMS2mJaUdEtGInJlRQBcRzhXT0GYdGIeAQAAdm9N6d+///jS9t++MewR5Mjbj5MAAAAASUVORK5CYII=",
  },
  {
    src: "/gallery/YP_Proposal_Full Res-21.jpg",
    width: 3306,
    height: 4959,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAM0lEQVR4nAEoANf/ACEdAEk+HldLMQAYAQCIcGGukoAANCUayb22zp6FANHIpP/50v/uxO1EEUFnBoIrAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_Full Res-33.jpg",
    width: 3395,
    height: 5093,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAM0lEQVR4nAEoANf/ACsdEEQ3JhcAAACum4/EsrFkPCwAj3ZmuZ+UvpWEAOrLvP/q1//45RZBExfol/haAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-168.jpg",
    width: 5408,
    height: 3605,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMklEQVR4nAEnANj/ADwjBzQaAENALUU+KwAXBQB0XUnIsqnt5NgArZaF+9a9//bl+ebX5x8R+0h4mywAAAAASUVORK5CYII=",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-174.jpg",
    width: 5472,
    height: 3648,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMklEQVR4nAEnANj/AHFsVD8sFW1JMUlHNABEMyMXAACQfnDRxbwAwqSSzbSj1rSd//bl9ZMQ+245LsEAAAAASUVORK5CYII=",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-176.jpg",
    width: 3648,
    height: 5472,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/AEk4IxQGABYKAABcRziUfW6km5EAyKSN3sCulIp/AMinkf/66vHYxwPcEl4WdJMQAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-194.jpg",
    width: 5472,
    height: 3648,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMElEQVR4nGOozIiSZ2CwU5aSYGBgmNJR526qtqoxozLWn+HR7YuFgfZTK1L+f7wDANcvDq5BFReOAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-198.jpg",
    width: 3648,
    height: 5472,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMUlEQVR4nGP4f/+UrbyEBAMDg7GKRLiNQaCNAUNLXvyUvJiLS3oYNq2c62Ws9v/TbQAGCw877t2Y8gAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-212.jpg",
    width: 3648,
    height: 5472,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/ABIBAHhpXSohFACSeGn/9+6NemgA+M+59tfG1bWiAP/l0fTOuf/fzWG2FpFnClMkAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-219.jpg",
    width: 3648,
    height: 5472,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMUlEQVR4nGOw0JIw15aQYGJg6K7Jn9PbGqAtydCYEbqgo2J5Uy7D63N7/7+8+v/LQwDwYhFCVImneQAAAABJRU5ErkJggg==",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-236.jpg",
    width: 3648,
    height: 5472,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/AP7z6f/78fzz6wCHfnNURzumloQALCchEQAAqJSGAODQwq2bi/Hp5NPyFfjNBWHgAAAAAElFTkSuQmCC",
  },
  {
    src: "/gallery/YP_Proposal_SM_Fin-47.jpg",
    width: 3365,
    height: 5047,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/ACQgAJ2QcpeNcAAZDAB7ZFBgSToAQjYqzruxvpaDAL60lPrsyP/40RKPEd4RpglyAAAAAElFTkSuQmCC",
  },
];
